services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: gc-next-db-prod
    ports:
      - "${NEXT_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db-prod:5432/gc_react_db?schema=public
    env_file:
      - .env.production
    depends_on:
      - db-prod
    restart: unless-stopped

  db-prod:
    image: postgres:latest
    container_name: gc-next-db-prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gc_react_db
    restart: unless-stopped

volumes:
  postgres_data_prod:

